services: 
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: strobosco/dockerbeginning:titanicbackend
    ports: 
      - "8080:8080"
  
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: strobosco/dockerbeginning:titanicfrontend
    ports: 
      - "3000:3000"
    links:
      - backend