apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: titanic
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: titanic
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: "docker.io/strobosco/dockerbeginning:titanicfrontend"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]