apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanicbackend
  labels:
    role: backend
spec:
  selector:
    matchLabels: 
      role: backend
  replicas: 1
  template:
    metadata:
      labels:
        role: backend
    spec:
      containers:
        - name: backend
          image: docker.io/strobosco/titanicfullstack:backend
          ports:
            - containerPort: 8080