apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanicfrontend
  labels:
    role: frontend
spec:
  selector:
    matchLabels:
      role: frontend
  replicas: 2
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/strobosco/titanicfullstack:frontend
          ports:
            - containerPort: 3000